# "Guía rápida de algebra lineal con Python + Numpy"
> "Guía rápida de Algebra lineal con Python + Numpy"

- toc: true
- branch: master
- badges: true
- comments: true
- categories: [python]
- image: images/framework.jpg
- hide: false
- search_exclude: true
- metadata_key1: metadata_value1
- metadata_key2: metadata_value2

Fuentes:
[numpy](https://numpy.org/) 

In [3]:
import numpy as np

In [ ]:
# Listas vs vectores de Numpy

In [7]:
# creación de listas y vectores
lista = [1,2,3,4]
vector = np.array([1,2,3,4]) # vector de numpy
print(lista)
print(vector)

[1, 2, 3, 4]
[1 2 3 4]


In [10]:
# Operaciones
print(lista+lista, "vs ", vector+vector )
print(lista*2 , "vs ",vector*2)

[1, 2, 3, 4, 1, 2, 3, 4] vs  [2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4] vs  [2 4 6 8]


In [18]:
# Matrices: creación
matriz1 = np.array([lista, lista, lista])
matriz2 = np.array([vector, vector, vector])  
matriz3 = np.array([lista,vector, [1, 1, 1, 1]])
matriz4 = np.array([[1,2,3,4]])  # matriz (1 x 4)

print(matriz1)
print(matriz2)
print(matriz3)
print(matriz4)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]
 [1 2 3 4]
 [1 1 1 1]]
[[1 2 3 4]]


In [14]:
# Matrices: escalado y translación
m_transformada = matriz1 * 2 + 1 
print(m_transformada)

[[3 5 7 9]
 [3 5 7 9]
 [3 5 7 9]]


In [15]:
# Matrices: operaciones elemento a elemento
matriz_suma = matriz1 + matriz1 
print(matriz_suma)
matriz_producto = matriz1 * matriz1
print(matriz_producto)

[[2 4 6 8]
 [2 4 6 8]
 [2 4 6 8]]
[[ 1  4  9 16]
 [ 1  4  9 16]
 [ 1  4  9 16]]


In [19]:
# Matrices: transpuesta
print (matriz1)
print(matriz1.shape)
print (matriz1.T)
print(matriz1.T.shape)
print (matriz4.T)
print(matriz4.T.shape)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
(3, 4)
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
(4, 3)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


$$ norm(\vec a) = ||\vec a|| = \sqrt {\sum_{i=1}^{n} a_i ^ 2}$$

In [25]:
# Matrices: norma
norma_vector = np.linalg.norm(vector)
norma_matriz = np.linalg.norm(matriz1)  # La matriz se toma como una lista de elementos
norma_matriz_col = np.linalg.norm(matriz1, axis=0)  # La matriz se toma como una lista de elementos
norma_matriz_fila = np.linalg.norm(matriz1, axis=1)  # La matriz se toma como una lista de elementos
print(norma_vector )
print(norma_matriz )
print(norma_matriz_col )
print(norma_matriz_fila )

5.477225575051661
9.486832980505138
[1.73205081 3.46410162 5.19615242 6.92820323]
[5.47722558 5.47722558 5.47722558]


$$\vec a \cdot \vec b = \sum_{i=1}^{n} a_i b_i$$

In [24]:
# Matrices: producto escalar
prod_escalar = np.dot(vector, vector)
print(prod_escalar)

30
